name: Deploy

on:
  push:
    branches:
      - cicd 

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: debian-12
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - uses: actions/setup-node@v3
        with:
          node-version: 22.14 
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: sudo apt-get install -y rsync wget && wget -q https://packages.microsoft.com/config/debian/$VERSION_ID/packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb
      - name: Run build script
        run: pwsh build.ps1 -version 11.2.6
#      - name: Setup key
#        run: echo '${{ secrets.DEPLOY_KEY }}' > ./upload.key && chmod 700 ./upload.key
#      - name: Build And Deploy
#        run: ./deploy.sh $DEPLOY_ARGS
