name: Deploy

on:
  push:
    branches:
      - cicd 

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: windows-latedt
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - uses: actions/setup-node@v3
        with:
          node-version: 22.14 
      - uses: pnpm/action-setup@v4
        with:
          version: 10.7.0
      - name: workloads 1
        run: dotnet workload restore ext/Avalonia/src/iOS/Avalonia.iOS/Avalonia.iOS.csproj
      - name: workloads 2
        run: dotnet workload restore ext/Avalonia/src/Android/Avalonia.Android/Avalonia.Android.csproj
      - name: Run build script
        run: ./build.ps1 -version 11.2.6
      - name: Find
        shell: bash
        run: find ./website/build
#      - name: Setup key
#        run: echo '${{ secrets.DEPLOY_KEY }}' > ./upload.key && chmod 700 ./upload.key
#      - name: Build And Deploy
#        run: ./deploy.sh $DEPLOY_ARGS
